### ISSUE TITLE
Concerning the function main.cpp/runBash capturing process return code

### ISSUE THREAD

**Issue by eriksank** [IonicaBizau/bat#33]
`runBash` is a really useful function. However, in my impression, there may be a few problems with the current implementation.

*  `runBash` does not do anything on failure to start the program.

It starts the program:

     process.start(command);

But what if the command does not even exist? Or something like that? It should return an error, but I can see from the documentation that QProcess.start returns `void`. So, I wonder if the Qt API even allows to detect if something went wrong at this point?

* `runBash` does not capture the exit code

Even though it certainly captures `stdout` and `stderr` streams:

        bashOutput->setProperty("stdout", stdout);
        bashOutput->setProperty("stderr", stderr);

it does not return what the exit code was. That is how pretty much all programs inform the caller that everything was normal, or that something went wrong. Therefore, without capture the exit code, things will become unreliable:

       int QProcess::exitCode()

Therefore, I think that we need something like:

        bashOutput->setProperty("exitCode", exitCode);

* Another concern is that the execution of the script will block the user interface. This can be a problem in some cases, such as waiting for the remote server to respond over the network. Therefore, I wonder what you would think of implementing an async version of `runBash` using:

      bool QProcess::startDetached(qint64 *pid = nullptr)

It could look similar to:

     runBashDetached(command, handlerFunc)

with `handlerFunc(bashOutput)` receiving `bashOutput` as its argument. The detached version is usually not needed when the command will just execute locally, but it may be troublesome to freeze the user interface for potentially slow network communications?
 
I am not an expert in Qt, but I would certainly be interested in helping to implement these things. Would you be interested in such fixes?

**Comment by IonicaBizau** [comment]
Indeed. Contributions are welcome!

My knowledge in C++ is not very good. I remember I just needed a good enough solution. :grin:

**Comment by eriksank** [comment]
Ok. Let me check.
